springdoc:
  # define target package of swagger scanning
  packages-to-scan: com.cheffi


spring:
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      # ddl-auto strategy
      ddl-auto: create

    properties:
      hibernate:
        # set default batch size
        default_batch_fetch_size: 100
    # turn OSIV off
    open-in-view: false

  data:
    redis:
      host: redis
      port: 6379

api:
  prefix: /api/v1


# monitoring setting start
management:
  #  server:
  #    port: 50000
  endpoint:
    httpexchanges:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      base-path: /cheffi-monitoring
      exposure:
        include:
          - health
          - info
          - beans
          - conditions
          - httpexchanges
          - metrics
          - prometheus
          - configprops
# monitoring setting end
