spring:
  profiles:
    group:
      "dev": "dev, oauth"
      "local": "local, oauth"
      "default": "local, oauth"
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      # ddl-auto strategy
      ddl-auto: create

    properties:
      hibernate:
        # show formatted sql
        format_sql: true
        show_sql: true

        # set default batch size
        default_batch_fetch_size: 100
    # turn OSIV off
    open-in-view: false

logging:
  level:
    com.cheffi.web.kakao.client: debug

springdoc:
  # define target package of swagger scanning
  packages-to-scan: com.cheffi

api:
  prefix: /api/v1
