spring:
  profiles:
    group:
      "dev": "dev, oauth, s3, actuator, dev-db, regions, swagger"
      "local": "local, oauth, s3, actuator, regions, swagger"
      "default": "local, oauth, s3, actuator, regions, swagger"
  config:
    import: classpath:data/application-regions.yml

  jpa:
    hibernate:
      # ddl-auto strategy
      ddl-auto: update

    properties:
        # set default batch size
        default_batch_fetch_size: 100
    # turn OSIV off
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    com.cheffi.web.kakao.client: debug

springdoc:
  # define target package of swagger scanning
  packages-to-scan: com.cheffi
  swagger-ui:
    tags-sorter: alpha

api:
  prefix: /api/v1


