management:

  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    logfile:
      enabled: true

  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - info
          - logfile

env:
  LOG_DIRECTORY: ${{ secrets.CHEFFI_DIRECTORY }}
