swagger:
  tag:
    sign-in: '01. 로그인'
    sign-up: '02. 회원가입'
    main: '03. 메인페이지'
    search: '04. 검색페이지'
    profile-info: '05. 프로필 조회'
    review-detail: '06. 리뷰 상세 페이지'
    review-cud: '07. 리뷰 등록, 수정, 삭제'
    profile-update: '08. 프로필 수정'
    follow: '09. 팔로우'
    tags: '10. 태그'
    notification: '11. 알림'
    cfc: '12. 쉐피코인 및 포인트'
    bookmark: '13. 찜(북마크)'
    region: '14. 지역구 조회'
    report: '15. 신고'
    block: '16. 차단'
    qna: '17. 자주 묻는 질문'
