name: Deploy to EC2

on:
  #pull_request:
  push:
    branches:
      - develop-CD-Test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradlew
      run: ./gradlew build -x test

    - name: SCP JAR to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.LSH_EC2_HOST }}
        username: ${{ secrets.LSH_EC2_USER }}
        key: ${{ secrets.LSH_EC2_KEY }}
        source: |
          "build/libs/*.jar"
          "./Dockerfile"
          "./Dockerfile-helper"
          "./docker-compose.yml"
          "./docker-compose-helper.yml"
        target: "/home/ec2-user/cheffifolder"

    - name: SSH Execute command on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LSH_EC2_HOST }}
        username: ${{ secrets.LSH_EC2_USER }}
        key: ${{ secrets.LSH_EC2_KEY }}
        script: |

          # 실행중인 app 종료
          # if lsof -Pi :8080 -sTCP:LISTEN -t >/dev/null ; then
          # echo "Port 8080 is already in use. Killing the process..."
          # kill $(lsof -t -i:8080)
          # fi
          
          cd /home/ec2-user/cheffifolder
          ls
          # nohup java -jar *.jar > /home/ec2-user/cheffifolder/cheffi.log 2>&1 &
