name: Deploy to EC2

on:
  push:
    branches:
      - cicdtest
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Copy Oauth key
        env:
          OAUTH_SECRET: ${{ secrets.OAUTH_SECRET }}
          OAUTH_SECRET_DIR: src/main/resources
          OAUTH_SECRET_DIR_FILE_NAME: application-oauth.yml
        run: echo $OAUTH_SECRET | base64 --decode > $OAUTH_SECRET_DIR/$OAUTH_SECRET_DIR_FILE_NAME

      - name: Copy S3 key
        env:
          S3_SECRET: ${{ secrets.S3_SECRET }}
          S3_SECRET_DIR: src/main/resources
          S3_SECRET_DIR_FILE_NAME: application-s3.yml
        run: echo $S3_SECRET | base64 --decode > $S3_SECRET_DIR/$S3_SECRET_DIR_FILE_NAME

      - name: Build with Gradlew
        env:
          CHEFFI_LOG_FOLDER_PATH: ${{ secrets.CHEFFI_LOG_FOLDER_PATH }}
        run: |
          export CHEFFI_DIRECTORY=$CHEFFI_LOG_FOLDER_PATH
          ./gradlew clean build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            build/libs/*.jar
            Dockerfile
            docker-compose.yml

  deploy:
    name: Deploy with SCP and Docker
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts

      - name: SCP JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "build/libs/*.jar, ./Dockerfile, ./docker-compose.yml"
          target: "/home/ec2-user/cheffifolder"

      - name: SSH Execute command on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ec2-user/cheffifolder
            docker-compose down --rmi local
            docker image prune -f
            docker-compose up --build -d

      # - name: Deployment Notification
      #   uses: 8398a7/action-slack@v3
      #   with:
      #     status: ${{ job.status }}
      #     author_name: dev-deploy-job
      #     text: 'dev-server-deployment'
      #     fields: repo,message,commit,author,ref,workflow,job,took,pullRequest
      #     mention: 'U05BT7J8YV8,U05BT2V4C58'
      #     if_mention: failure
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      #   if: always() # Pick up events even if the job fails or is canceled.
