name: Deploy to EC2

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Copy Oauth key
        env:
          OAUTH_SECRET: ${{ secrets.OAUTH_SECRET }}
          OAUTH_SECRET_DIR: src/main/resources
          OAUTH_SECRET_DIR_FILE_NAME: application-oauth.yml
        run: echo $OAUTH_SECRET | base64 --decode > $OAUTH_SECRET_DIR/$OAUTH_SECRET_DIR_FILE_NAME

      - name: Build with Gradlew
        run: ./gradlew clean build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            build/libs/*.jar


  deploy:
    name: Deploy with SCP and Docker
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
    
      - name: SCP JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LSH_EC2_HOST }}
          username: ${{ secrets.LSH_EC2_USER }}
          key: ${{ secrets.LSH_EC2_KEY }}
          source: "./*.jar, ./Dockerfile, ./docker-compose.yml"
          target: "/home/ec2-user/cheffifolder"

      - name: SSH Execute command on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LSH_EC2_HOST }}
          username: ${{ secrets.LSH_EC2_USER }}
          key: ${{ secrets.LSH_EC2_KEY }}
          script: |
            cd /home/ec2-user/cheffifolder
            docker-compose down --rmi local
            docker image prune -f
            docker-compose up --build -d
