name: Deploy to EC2

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradlew
        run: ./gradlew build -x test

      - name: SCP JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LSH_EC2_HOST }}
          username: ${{ secrets.LSH_EC2_USER }}
          key: ${{ secrets.LSH_EC2_KEY }}
          source: "build/libs/*.jar, ./Dockerfile, ./Dockerfile-helper, ./docker-compose.yml , ./docker-compose-helper.yml"
          target: "/home/ec2-user/cheffifolder"

      - name: SSH Execute command on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LSH_EC2_HOST }}
          username: ${{ secrets.LSH_EC2_USER }}
          key: ${{ secrets.LSH_EC2_KEY }}
          script: |
            cd /home/ec2-user/cheffifolder
            docker-compose -p cheffi-server build
            docker-compose -p cheffi-server up -d